build:
  uri: https://github.com/tommaso-borgato/wildfly-distributed-sessions-infinispan.git
  ref: main
  s2i:
    buildApplicationImage: true
deploy:
  env:
    - name: INFINISPAN_SERVER_HOST
      value: 'example-infinispan'
    - name: INFINISPAN_SERVER_PORT
      value: '11222'
    - name: INFINISPAN_SERVER_TRUST_STORE_FILENAME
      value: '/distributed-sessions-infinispan/example-infinispan.crt'
    - name: INFINISPAN_SERVER_USER
      value: 'foo'
    - name: INFINISPAN_SERVER_PASSWORD
      value: 'bar'
  volumes:
    - name: connect-secret-crt-volume
      secret:
        secretName: example-infinispan-certificate-crt
  volumeMounts:
    - name: connect-secret-crt-volume
      mountPath: '/distributed-sessions-infinispan'